---
resolver: lts-11.1
packages:
  - '.'
extra-deps:
- git: https://github.com/waddlaw/pandoc
  commit: 2b6b176aeefcb7bf26c81fb3d5978fcebd6c1615
- pandoc-types-1.17.4.2
- git: https://github.com/st3ll1s/haddock
  commit: b3912d70f74b0693f1ea8cffb8f547b1303ef325
  subdirs:
  - haddock-library